feat: modernize dmscripts
- Removed obsolete scripts
- Refactor common functionality
- Improve configurability
- Enhance script consistency

diff --git a/scripts/dm-dictionary b/scripts/dm-dictionary
--- a/scripts/dm-dictionary
+++ b/scripts/dm-dictionary
@@ -14,89 +14,83 @@
 
 set -euo pipefail
 
-_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
-if [[ -f "${_path}/_dm-helper.sh" ]]; then
-    # shellcheck disable=SC1090,SC1091
-    source "${_path}/_dm-helper.sh"
-else
-    # shellcheck disable=SC1090
-    echo "No helper-script found"
+# shellcheck disable=SC1091
+source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null
+
+source_dmscripts_configs
+
+if configs_are_different; then
+  echo "$(date): configs are different" >>"${DM_CONFIG_DIFF_LOGFILE}"
+  sleep 1
 fi
 
-# script will not hit this if there is no config-file to load
-# shellcheck disable=SC1090
-source "$(get_config)"
-
-# Check if config has updates that should be displayed to the user
-check_updated_config
-
 main() {
-    # dmenu expects some sort of input piped into it.
-    # The echo to /dev/null is just a hacky way of giving
-    # dmenu some input without really giving any input.
-    # shellcheck disable=SC2260
-    WORD="$(echo "" >/dev/null | ${MENU} "Enter word to lookup:")"
-    TESTWORD="$(dym -c -n=1 "$WORD")"
+  # dmenu expects some sort of input piped into it.
+  # The echo to /dev/null is just a hacky way of giving
+  # dmenu some input without really giving any input.
+  # shellcheck disable=SC2260
+  word="$(echo "" >/dev/null | ${MENU} "Enter word to lookup:")"
+  testword="$(dym -c -n=1 "${word}")"
 
-    if [ "$WORD" != "$TESTWORD" ]; then
-        KEYWORD=$(dym -c "$WORD" | ${MENU} "was $WORD a misspelling?(select/no)")
-        if [ "$KEYWORD" = "no" ] || [ "$KEYWORD" = "n" ]; then
-            KEYWORD="$WORD"
-        fi
-    else
-        KEYWORD="$WORD"
+  if [[ "${word}" != "${testword}" ]]; then
+    keyword=$(dym -c "${word}" | ${MENU} "was ${word} a misspelling?(select/no)")
+    if [[ "${keyword}" = "no" ]] || [[ "${keyword}" = "n" ]]; then
+      keyword="${word}"
     fi
+  else
+    keyword="${word}"
+  fi
 
-    if ! [ "${KEYWORD}" ]; then
-        printf 'No word inserted\n' >&2
-        exit 0
-    fi
-    $DMTERM trans -v -d "$KEYWORD"
+  if ! [[ -n "${keyword}" ]]; then
+    printf 'No word inserted\n' >&2
+    exit 0
+  fi
+  ${DMTERM} trans -v -d "${keyword}"
 }
 
 mainfzf() {
-    # shellcheck disable=SC2260
-    WORD="$(echo " " | fzf --bind 'return:print-query' --prompt "Enter word to lookup:")"
-    TESTWORD="$(dym -c -n=1 "$WORD")"
+  # shellcheck disable=SC2260
+  word="$(echo " " | fzf --bind 'return:print-query' --prompt "Enter word to lookup:")"
+  testword="$(dym -c -n=1 "${word}")"
 
-    if [ "$WORD" != "$TESTWORD" ]; then
-        # shellcheck disable=SC2153
-        KEYWORD=$(dym -c "$WORD" | ${FMENU} "was $WORD a misspelling?(select/no)")
-        if [ "$KEYWORD" = "no" ] || [ "$KEYWORD" = "n" ]; then
-            KEYWORD="$WORD"
-        fi
-    else
-        KEYWORD="$WORD"
+  if [[ "${word}" != "${testword}" ]]; then
+    # shellcheck disable=SC2153
+    keyword=$(dym -c "${word}" | ${FMENU} "was ${word} a misspelling?(select/no)")
+    if [[ "${keyword}" = "no" ]] || [[ "${keyword}" = "n" ]]; then
+      keyword="${word}"
     fi
+  else
+    keyword="${word}"
+  fi
 
-    if ! [ "${KEYWORD}" ]; then
-        printf 'No word inserted\n' >&2
-        exit 0
-    fi
-    $DMTERM trans -v -d "$KEYWORD"
+  if ! [[ -n "${keyword}" ]]; then
+    printf 'No word inserted\n' >&2
+    exit 0
+  fi
+  ${DMTERM} trans -v -d "${keyword}"
 }
 
-noOpt=1
+no_opt=1
 # If script is run with '-d', it will use 'dmenu'
 # If script is run with '-f', it will use 'fzf'
 # If script is run with '-d', it will use 'rofi'
 while getopts "dfrh" arg 2>/dev/null; do
-    case "${arg}" in
-    d) # shellcheck disable=SC2153
-        MENU=${DMENU}
-        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
-        ;;
-    f) # shellcheck disable=SC2153
-        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && mainfzf ;;
-    r) # shellcheck disable=SC2153
-        MENU=${RMENU}
-        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@"
-        ;;
-    h) help ;;
-    *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
-    esac
-    noOpt=0
+  case "${arg}" in
+  d) # shellcheck disable=SC2153
+    MENU=${DMENU}
+    [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
+    ;;
+  f) # shellcheck disable=SC2153
+    [[ "${BASH_SOURCE[0]}" == "${0}" ]] && mainfzf ;;
+  r) # shellcheck disable=SC2153
+    MENU=${RMENU}
+    [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@"
+    ;;
+  h) help ;;
+  *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
+  esac
+  no_opt=0
 done
 
 # If script is run with NO argument, it will use 'dmenu'
-[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+[[ "${no_opt}" = 1 ]] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
diff --git a/scripts/dm-sounds b/scripts/dm-sounds
--- a/scripts/dm-sounds
+++ b/scripts/dm-sounds
@@ -18,102 +18,72 @@
 # get hidden bugs that are hard to discover.
 set -euo pipefail
 
-_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
-if [[ -f "${_path}/_dm-helper.sh" ]]; then
-    # shellcheck disable=SC1090,SC1091
-    source "${_path}/_dm-helper.sh"
-else
-    # shellcheck disable=SC1090
-    echo "No helper-script found"
+# shellcheck disable=SC1091
+source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null
+
+source_dmscripts_configs
+
+if configs_are_different; then
+  echo "$(date): configs are different" >>"$DM_CONFIG_DIFF_LOGFILE"
+  sleep 1
 fi
 
-# script will not hit this if there is no config-file to load
-# shellcheck disable=SC1090
-source "$(get_config)"
-
-# Check if config has updates that should be displayed to the user
-check_updated_config
-
 main() {
-    # Check if sounds_dir is a real directory
-    # shellcheck disable=SC2154
-    [ ! -d "${sounds_dir}" ] && err "The dm-sounds folder could not be found.
+  # Check if sounds_dir is a real directory
+  # shellcheck disable=SC2154
+  [ ! -d "${sounds_dir}" ] && err "The dm-sounds folder could not be found.
 Place your sounds in:  ${sounds_dir}
 Here are 15 sounds that you can download:
 https://gitlab.com/dtos/etc/dtos-dmscripts/-/tree/main/etc/dtos/.config/dmscripts/dmsounds"
-    # Produces a listing of the sound files.
-    # shellcheck disable=SC2154
-    readarray -t _sounds_list < <(find "${sounds_dir}" \( -iname "*.mp3" -o -iname "*.m4a" -o -iname "*.ogg" \) -printf '%P\n')
+  # Produces a listing of the sound files.
+  # shellcheck disable=SC2154
+  readarray -t _sounds_list < <(find "${sounds_dir}" \( -iname "*.mp3" -o -iname "*.m4a" -o -iname "*.ogg" \) -printf '%P\n')
 
-    echo "${_sounds_list[*]}"
+  echo "${_sounds_list[*]}"
 
-    # An array of options to choose.
-    local _options=(
-        "Choose sound file"
-        "Play random sound"
-        "Stop sound player"
-        "Quit"
-    )
+  # An array of options to choose.
+  local _options=(
+    "Choose sound file"
+    "Play random sound"
+    "Stop sound player"
+    "Quit"
+  )
 
-    # Piping the _options array into dmenu.
+  # Piping the _options array into dmenu.
+  # We use "printf '%s\n'" to format the array one item to a line.
+  choice=$(printf '%s\n' "${_options[@]}" | ${MENU} 'Ambient sounds:')
+
+  if [ "$choice" == "Choose sound file" ]; then
+    # Piping the soundList array into dmenu.
     # We use "printf '%s\n'" to format the array one item to a line.
-    choice=$(printf '%s\n' "${_options[@]}" | ${MENU} 'Ambient sounds:' "${@}")
+    choice=$(printf '%s\n' "${_sounds_list[@]}" | sort | ${MENU} 'Choose sound file:')
+    # Kill PID saved in cache file.
+    kill "$(cat "$HOME/.cache/dmsounds")" || echo "mpv was not running."
+    # Play the chosen sound file.
+    # shellcheck disable=SC2154
+    mpv --no-video --loop "$sounds_dir/$choice" >/dev/null 2>&1 &
+    # Get PID for the above command and write to cache.
+    _pid=$!
+    echo "$_pid" >"$HOME/.cache/dmsounds"
 
-    if [ "$choice" == "Choose sound file" ]; then
-        # Piping the soundList array into dmenu.
-        # We use "printf '%s\n'" to format the array one item to a line.
-        choice=$(printf '%s\n' "${_sounds_list[@]}" | sort | ${MENU} 'Choose sound file:' "$@")
-        # Kill PID saved in cache file.
-        kill "$(cat "$HOME/.cache/dmsounds")" || echo "mpv was not running."
-        # Play the chosen sound file.
-        # shellcheck disable=SC2154
-        mpv --no-video --loop "$sounds_dir/$choice" >/dev/null 2>&1 &
-        # Get PID for the above command and write to cache.
-        _pid=$!
-        echo "$_pid" >"$HOME/.cache/dmsounds"
+  elif [ "$choice" == "Play random sound" ]; then
+    get_rand=$(printf '%s\n' "${_sounds_list[@]}" | shuf -n 1)
+    # Kill PID saved in cache file.
+    kill "$(cat "$HOME/.cache/dmsounds")" || echo "mpv was not running."
+    # Play random sound file.
+    mpv --no-video --loop "$sounds_dir/$get_rand" >/dev/null 2>&1 &
+    # ffplay -nodisp -loop 0 "$sounds_dir/$get_rand" &
+    # Get PID for the above command and write to cache.
+    _pid=$!
+    echo "$_pid" >"$HOME/.cache/dmsounds"
 
-    elif [ "$choice" == "Play random sound" ]; then
-        getRand=$(printf '%s\n' "${_sounds_list[@]}" | shuf -n 1)
-        # Kill PID saved in cache file.
-        kill "$(cat "$HOME/.cache/dmsounds")" || echo "mpv was not running."
-        # Play random sound file.
-        mpv --no-video --loop "$sounds_dir/$getRand" >/dev/null 2>&1 &
-        # ffplay -nodisp -loop 0 "$sounds_dir/$getRand" &
-        # Get PID for the above command and write to cache.
-        _pid=$!
-        echo "$_pid" >"$HOME/.cache/dmsounds"
+  elif [ "$choice" == "Stop sound player" ]; then
+    kill "$(cat "$HOME/.cache/dmsounds")" || echo "mpv was not running."
 
-    elif [ "$choice" == "Stop sound player" ]; then
-        kill "$(cat "$HOME/.cache/dmsounds")" || echo "mpv was not running."
-
-    else
-        echo "Program terminated." && exit 0
-    fi
+  else
+    echo "Program terminated." && exit 0
+  fi
 }
 
-noOpt=1
-# If script is run with '-d', it will use 'dmenu'
-# If script is run with '-f', it will use 'fzf'
-# If script is run with '-d', it will use 'rofi'
-while getopts "dfrh" arg 2>/dev/null; do
-    case "${arg}" in
-    d) # shellcheck disable=SC2153
-        MENU=${DMENU}
-        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
-        ;;
-    f) # shellcheck disable=SC2153
-        MENU=${FMENU}
-        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
-        ;;
-    r) # shellcheck disable=SC2153
-        MENU=${RMENU}
-        [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "@"
-        ;;
-    h) help ;;
-    *) printf '%s\n' "Error: invalid option" "Type $(basename "$0") -h for help" ;;
-    esac
-    noOpt=0
-done
-
-# If script is run with NO argument, it will use 'dmenu'
-[ $noOpt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
+MENU="$(get_menu_program "$@")"
+[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main
